### PR TITLE
feat: input dto validation

### PR DESCRIPTION
**Pull request by otavlna**

### CODE REVIEW

**Comment by MartinPl0** [comment]
Nothing needs to be changed in the swagger documentation for it to reflect it? I don't have much experience with it so just asking.

**Comment by otavlna** [comment]
We could specify that all endpoints could throw 400. However, I don't know if I need to manually change all jsdoc swagger comments, or whether we used some automated tool to generate those jsdoc swagger comments. I asked @hajekad on Teams, currently waiting for answer

**Comment by MartinPl0** [comment]
I understand, it was just a food for thought, regarding the second PR I don't see any visible code errors, still would like for Adam to review it, bit too complex for my node backend knowledge and not sure if the conventions are handled correctly (not that they are not). Will tackle it if needed to move on.

**Comment by MartinPl0** [comment]
Yeah, I merged your branch with the test one and the tests are still failing, If you go to https://github.com/Project-team-DL-7/Task-Manager/blob/4f42ed3bac4e3915f8c17fd2c5c05b3dacbed0f5/test/project.controller.test.js#L330 the controllers still do not return 400 on invalid data, I believe the test is written correctly right? We are just not handling the 400. You even mentioned it :D https://github.com/Project-team-DL-7/Task-Manager/pull/10#discussion_r1408148715.

**Pull request merged**
